/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D TORRECASTILLO.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom002"].geometry}
        material={materials["TQ_ARD_front.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom002_1"].geometry}
        material={materials.TQ_ARD_back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom002_2"].geometry}
        material={materials.TQ_ARD_edge}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["TQ_ARD-geom002_3"].geometry}
        material={materials["TQ_ARD_front.003"]}
      />
    </group>
  );
}

useGLTF.preload("/3D TORRECASTILLO.gltf");
